#!/bin/sh

# Example for $XDG_CONFIG_HOME/swiv/exec/key-handler
# Called by swiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# swiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the xkb
# keysym as listed in /usr/include/xkbcommon/xkbcommon-keysyms.h without the
# "XKB_KEY_" prefix.

rotate() {
	degree="$1"
	tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
		case "$(file -b -i "$file")" in
		image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
		*)           mogrify  -rotate "$degree" "$file" ;;
		esac
	done
}

case "$1" in
"C-x")  wl-copy -n ;;
"C-c")  while read file; do wl-copy -t image/png < "$file"; done ;;
"C-e")  while read file; do foot sh -c "exiv2 pr -q -pa '$file' | less" & done ;;
"C-g")  tr '\n' '\0' | xargs -0 gimp & ;;
"C-r")  while read file; do rawtherapee "$file" & done ;;
"C-comma")  rotate 270 ;;
"C-period") rotate  90 ;;
"C-slash")  rotate 180 ;;
esac
